# Generated by Django 4.0.4 on 2022-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contact_business_alter_contact_ui_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='business',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ui',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='web',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
    ]
